# Generated by Django 3.2.4 on 2021-06-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
