# Generated by Django 3.2.4 on 2021-06-18 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('growDataAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tent',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cycleRecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='growDataAPI.cycle')),
            ],
        ),
    ]
