# Generated by Django 3.2.4 on 2021-07-14 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('growDataAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tent',
            old_name='lightModel',
            new_name='lightWatts',
        ),
    ]
