# Generated by Django 3.2.4 on 2021-06-18 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('growDataAPI', '0002_tent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tent',
            old_name='cycleRecord',
            new_name='cycle',
        ),
    ]
