# Generated by Django 3.2.4 on 2021-06-23 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('growDataAPI', '0003_rename_cyclerecord_tent_cycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seed', models.BooleanField(default=False)),
                ('clone', models.BooleanField(default=False)),
                ('tent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='growDataAPI.tent')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='growDataAPI.plant')),
                ('tent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='growDataAPI.tent')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor_Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('temp', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='growDataAPI.sensor')),
            ],
        ),
    ]
