# Generated by Django 3.2.4 on 2021-07-14 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('growDataAPI', '0003_auto_20210714_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='growDataAPI.plant'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='tent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='growDataAPI.tent'),
        ),
    ]
