# Generated by Django 3.2.4 on 2021-07-30 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growDataAPI', '0005_auto_20210723_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor_data',
            name='humidity',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='sensor_data',
            name='temp',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name=''),
        ),
    ]
